GPUID: 0
WORKERS: 1
PRINT_FREQ: 10 # 多少个step打印一次训练信息
SAVE_FREQ: 1 # 多少个epoch保存一次
EVAL_FREQ: 1 # 多少个epoch评估一次
PIN_MEMORY: False
OUTPUT_DIR: 'output' # 保存路径
BLANK_CHAR: '-' # 空白占位符的字符

CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True

DATASET:
  DATASET: 360CC
  ROOT: "data/dataset/" # 图片路径
  CHAR_FILE: 'data/labels/figure.txt' # 字典路径
  JSON_FILE: {'train': 'data/labels/train.txt', 'val': 'data/labels/val.txt'} # 训练集测试集
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  STD: 0.193
  MEAN: 0.588
  ALPHABETS: ''

TRAIN:
  BATCH_SIZE_PER_GPU: 32
  SHUFFLE: True
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  RESUME:
    IS_RESUME: False
    FILE: ''
  OPTIMIZER: 'adam'
  LR: 0.0001
  WD: 0.0
  LR_STEP: [60, 80]
  LR_FACTOR: 0.1
  MOMENTUM: 0.0
  NESTEROV: False
  RMSPROP_ALPHA:
  RMSPROP_CENTERED:
  FINETUNE:
    IS_FINETUNE: true
    FINETUNE_CHECKPOINIT: 'output/checkpoints/digital_recognition.pth'
    FREEZE: true

TEST:
  BATCH_SIZE_PER_GPU: 16
  SHUFFLE: True  # for random test rather than test on the whole validation set
  NUM_TEST_BATCH: 1000
  NUM_TEST_DISP: 10

MODEL:
  NAME: 'crnn'
  IMAGE_SIZE:
    OW: 280 # origial width: 280
    H: 32
    W: 160   # resized width: 160
  NUM_CLASSES: 0
  NUM_HIDDEN: 10
